# Generated by Django 4.1.7 on 2023-06-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseName', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course')),
                ('courseFee', models.IntegerField()),
                ('courseDuration', models.IntegerField()),
                ('syllabus', models.CharField(default='', max_length=500)),
                ('aboutCourse', models.CharField(default='', max_length=1000)),
                ('stars', models.IntegerField(default=3)),
            ],
        ),
    ]
